name: ${project.artifactId}
main: ${project.groupId}.bukkit.${project.artifactId}
description: ${project.name}
version: ${project.version}
author: xXSchrandXx
website: https://www.gamestrike.de
api-version: 1.13
softdepend: []
commands:
  serverstatussigns:
    description: Hauptkommando von ServerStatusSigns.
    aliases: [sss]
    usage: /sss <> []